/*
 * This Java source file was generated by the Gradle 'init' task.
 * Spring dependencies has been added manually
 */
package com.gmail.gremlin.gosha;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
